### ISSUE TITLE
Reproducing results

### ISSUE THREAD

**Issue by carlos-gemmell** [jzbjyb/OmniTab#1]
Hi,

Thanks for the cool work you've done! Keen to take a look at how the models perform.
Can your paper results be reproduced with the current code setup?
What is needed to do this?

**Comment by jzbjyb** [comment]
Hi, thanks for your interest! You can follow the [instructions](https://github.com/jzbjyb/OmniTab#conda) to setup the conda environment and use the [released model checkpoint](https://github.com/jzbjyb/OmniTab#pretrained-models-and-data) to [generate predictions](https://github.com/jzbjyb/OmniTab#inference) on the WikiTableQuestions dataset.

**Comment by carlos-gemmell** [comment]
Hi Zhengbao,

Thanks for the update on this! 
Would it be possible to upload your dev predictions in addition to the test please?

**Comment by jzbjyb** [comment]
Sure! Please see the updated ["pretrained models and data"](https://github.com/jzbjyb/OmniTab#pretrained-models-and-data) section to download predictions on both dev and test split of WTQ.
