### ISSUE TITLE
How to generate preprocessed data?

### ISSUE THREAD

**Issue by LinWeizheDragon** [jzbjyb/OmniTab#2]
Hi,

Thanks for sharing your work and your code. I am writing to ask a silly question: how can I generate the data used for training and testing? From the code, it seems that they were loaded from some preprocessed .h5 files. Which command I should run to generate these files?
Correct me if I am wrong!
Thanks in advance!

**Comment by LinWeizheDragon** [comment]
Be more specific: how to generate preprocessed wtq data, as in `OmniTab/omnitab_download/wtq/test/epoch_0.shard0.h5`

**Comment by jzbjyb** [comment]
Hi, thanks for the question! You can use [test_wikitablequestions.sh](https://github.com/jzbjyb/OmniTab/blob/main/test_wikitablequestions.sh) to run inference on the WTQ dataset which automatically handles data downloading and processing.
